# Generated by Django 5.2.1 on 2025-08-29 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scholarships", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="tags",
            field=models.ManyToManyField(
                related_name="profiles", to="scholarships.tag"
            ),
        ),
        migrations.RemoveField(
            model_name="profile",
            name="level",
        ),
        migrations.AlterField(
            model_name="scholarship",
            name="level",
            field=models.ManyToManyField(
                blank=True, related_name="scholarships", to="scholarships.level"
            ),
        ),
        migrations.AlterField(
            model_name="scholarship",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="scholarships", to="scholarships.tag"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="level",
            field=models.ManyToManyField(
                related_name="profiles", to="scholarships.level"
            ),
        ),
    ]
