# Generated by Django 5.2.1 on 2025-06-14 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scholarships", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="scholarship",
            name="source",
            field=models.CharField(default="none"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="scholarship",
            name="scrape_event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="scholarships",
                to="scholarships.scholarshipscrapeevent",
            ),
        ),
    ]
