# Generated by Django 5.2.1 on 2025-08-29 21:27

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scholarships", "0002_profile_tags_remove_profile_level_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="scholarship",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 8, 29, 21, 27, 13, 574361, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="bookmark",
            name="scholarship",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookmarks",
                to="scholarships.scholarship",
            ),
        ),
    ]
