# Generated by Django 5.2.1 on 2025-09-23 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scholarships", "0003_alter_scholarship_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scholarship",
            name="eligibility",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="scholarship",
            name="fingerprint",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="scholarship",
            name="requirements",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="scholarship",
            name="reward",
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name="scholarship",
            name="slug",
            field=models.SlugField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="scholarship",
            name="source",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
