# Generated by Django 5.2.1 on 2025-08-29 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scholarships", "0003_scholarship_created_at_alter_bookmark_scholarship"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scholarship",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
