# Generated by Django 5.2.1 on 2025-08-29 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scholarships", "0004_alter_scholarship_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(
                choices=[
                    ("international", "International"),
                    ("merit", "Merit"),
                    ("need", "Need"),
                    ("general", "General"),
                ],
                max_length=50,
                unique=True,
            ),
        ),
    ]
