# Generated by Django 5.2.1 on 2025-08-30 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scholarships", "0005_alter_tag_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="level",
            field=models.ManyToManyField(
                blank=True, related_name="profiles", to="scholarships.level"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="profiles", to="scholarships.tag"
            ),
        ),
    ]
