# Generated by Django 5.2.1 on 2025-08-31 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scholarships", "0006_alter_profile_level_alter_profile_tags"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScrapeFailureLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField()),
                ("error", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("retried", models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name="scholarship",
            unique_together={("title", "link")},
        ),
        migrations.AddField(
            model_name="scholarship",
            name="fingerprint",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.RemoveField(
            model_name="scholarship",
            name="slug",
        ),
    ]
