# Generated by Django 5.2.1 on 2025-09-02 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "scholarships",
            "0007_scrapefailurelog_alter_scholarship_unique_together_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="scholarship",
            name="slug",
            field=models.SlugField(blank=True, null=True),
        ),
    ]
