# Generated by Django 5.2.1 on 2025-09-23 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scholarships", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scholarship",
            name="link",
            field=models.URLField(max_length=1000),
        ),
    ]
