# Generated by Django 5.2.1 on 2025-09-23 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scholarships", "0002_alter_scholarship_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scholarship",
            name="slug",
            field=models.SlugField(blank=True, max_length=500, null=True),
        ),
    ]
