# Generated by Django 5.2.1 on 2025-10-29 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scholarships", "0004_alter_scholarship_eligibility_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("base_url", models.URLField()),
                (
                    "list_url",
                    models.URLField(
                        help_text="The page containing scholarship listings"
                    ),
                ),
                (
                    "list_item_selector",
                    models.CharField(
                        help_text="Selector for each scholarship card", max_length=255
                    ),
                ),
                ("title_selector", models.CharField(max_length=255)),
                ("link_selector", models.CharField(max_length=255)),
                (
                    "description_selector",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "eligibility_selector",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "requirements_selector",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "deadline_selector",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "start_date_selector",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "reward_selector",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "level_selector",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "tag_selector",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("active", models.BooleanField(default=True)),
                ("last_successful", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True, null=True)),
                ("last_scraped", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
