# Generated by Django 5.2.1 on 2025-11-19 21:13

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scholarships", "0005_siteconfig_alter_user_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="embedding",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.FloatField(), blank=True, null=True, size=None
            ),
        ),
        migrations.AddField(
            model_name="scholarship",
            name="embedding",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.FloatField(), blank=True, null=True, size=None
            ),
        ),
    ]
