# Generated by Django 5.2.1 on 2025-11-29 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scholarships", "0006_profile_embedding_scholarship_embedding"),
    ]

    operations = [
        migrations.AddField(
            model_name="scholarship",
            name="scraped_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="FailedScholarship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(max_length=1000)),
                ("reason", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("retries", models.IntegerField(default=0)),
                (
                    "scrape_event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="failed_items",
                        to="scholarships.scholarshipscrapeevent",
                    ),
                ),
            ],
        ),
    ]
