# Generated by Django 5.2.1 on 2025-12-27 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0007_scholarship_scraped_at_failedscholarship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarship',
            name='eligibility',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='requirements',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
