# Generated by Django 5.2.1 on 2026-01-11 18:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0008_alter_scholarship_eligibility_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarship',
            name='is_recurring',
            field=models.BooleanField(default=False, help_text='True if this scholarship reopens annually.'),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='last_renewed_at',
            field=models.DateTimeField(blank=True, help_text='The last time we detected a new cycle for this item.', null=True),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('expired', 'Expired')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='scraped_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.CreateModel(
            name='ScholarshipCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deadline', models.DateField(null=True)),
                ('batch_year', models.IntegerField(db_index=True)),
                ('status', models.CharField(default='active', max_length=20)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
                ('scholarship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycles', to='scholarships.scholarship')),
            ],
        ),
        migrations.CreateModel(
            name='WatchedScholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notified_for_year', models.DateTimeField(blank=True, null=True)),
                ('notified', models.BooleanField(default=False)),
                ('scholarship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scholarships.scholarship')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'scholarship')},
            },
        ),
    ]
