# Generated by Django 5.2.1 on 2026-01-24 09:39
from pgvector.django import VectorExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships',  '0010_scrapesubmission'),
    ]

    operations = [
        VectorExtension()
    ]
