# Generated by Django 5.2.1 on 2026-01-24 09:44

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0012_enable_pgvector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarship',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True),
        ),
    ]
