# Generated by Django 5.2.1 on 2026-01-24 10:22

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0013_alter_scholarship_embedding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True),
        ),
    ]
