# Generated by Django 5.2.1 on 2026-02-25 07:26

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0014_alter_profile_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='academic_achievements',
            field=models.TextField(blank=True, help_text='Awards, honours, GPA, publications, research.'),
        ),
        migrations.AddField(
            model_name='profile',
            name='career_goals',
            field=models.TextField(blank=True, help_text='What do you want to do in 5-10 years and why.'),
        ),
        migrations.AddField(
            model_name='profile',
            name='challenges_overcome',
            field=models.TextField(blank=True, help_text='A significant obstacle you faced and how you dealt with it.'),
        ),
        migrations.AddField(
            model_name='profile',
            name='community_impact',
            field=models.TextField(blank=True, help_text='Volunteering, social impact, community work.'),
        ),
        migrations.AddField(
            model_name='profile',
            name='extracurriculars',
            field=models.TextField(blank=True, help_text='Clubs, sports, hobbies, side projects.'),
        ),
        migrations.AddField(
            model_name='profile',
            name='financial_need_statement',
            field=models.TextField(blank=True, help_text='Optional. Describe your financial background if relevant.'),
        ),
        migrations.AddField(
            model_name='profile',
            name='gpa',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='On a 4.0 or 5.0 scale — specify in gpa_scale.', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='gpa_scale',
            field=models.DecimalField(blank=True, decimal_places=1, default=4.0, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='languages_spoken',
            field=models.JSONField(blank=True, default=list, help_text="[{'language': 'English', 'level': 'Native'}]"),
        ),
        migrations.AddField(
            model_name='profile',
            name='leadership_experience',
            field=models.TextField(blank=True, help_text='Describe a time you led a team or initiative.'),
        ),
        migrations.AddField(
            model_name='profile',
            name='research_experience',
            field=models.TextField(blank=True, help_text='Research projects, papers, labs, supervisors.'),
        ),
        migrations.AddField(
            model_name='profile',
            name='technical_skills',
            field=models.JSONField(blank=True, default=list, help_text="['Python', 'Django', 'Machine Learning']"),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, help_text='Short personal summary (2-3 sentences). Shown publicly.'),
        ),
        migrations.AlterField(
            model_name='scrapesubmission',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
        migrations.CreateModel(
            name='ProfileChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_type', models.CharField(choices=[('leadership', 'Leadership Experience'), ('academic', 'Academic Achievements'), ('financial_need', 'Financial Need'), ('career_goals', 'Career Goals'), ('community_impact', 'Community Impact'), ('challenges', 'Challenges Overcome'), ('research', 'Research Experience'), ('extracurriculars', 'Extracurriculars'), ('bio', 'Bio Summary')], max_length=50)),
                ('text', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='scholarships.profile')),
            ],
            options={
                'indexes': [models.Index(fields=['profile', 'chunk_type'], name='scholarship_profile_928dd6_idx')],
                'unique_together': {('profile', 'chunk_type')},
            },
        ),
    ]
