# Generated by Django 5.2.1 on 2026-02-25 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0015_profile_academic_achievements_profile_career_goals_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='relevant_coursework',
            field=models.TextField(blank=True, help_text='school work and what you learned from them'),
        ),
    ]
