# Generated by Django 5.2.1 on 2026-03-07 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0016_profile_relevant_coursework'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfig',
            name='list_url',
        ),
        migrations.CreateModel(
            name='ListingSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(help_text='The specific category/listing URL (e.g., Undergraduate feed)')),
                ('category_name', models.CharField(blank=True, help_text='e.g., Masters, STEM, Africa', max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='scholarships.siteconfig')),
            ],
        ),
    ]
