# Generated by Django 5.2.1 on 2026-03-12 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0017_remove_siteconfig_list_url_listingsource'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='receives_email_reminders',
            field=models.BooleanField(default=True),
        ),
    ]
