# Generated by Django 5.2.1 on 2026-03-17 07:35

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0018_user_receives_email_reminders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True),
        ),
    ]
