services:
  - type: web
    name: scholarscope-web
    env: python
    buildCommand: |
      pip install --upgrade pip setuptools wheel
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: |
      python manage.py migrate
      gunicorn scholarscope.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: REDIS_URL
        sync: false
      - key: DATABASE_URL
        sync: false

  - type: worker
    name: scholarscope-worker
    env: python
    buildCommand: |
      pip install --upgrade pip setuptools wheel
      pip install -r requirements.txt
    startCommand: celery -A scholarscope worker -l info
    envVars:
      - key: REDIS_URL
        sync: false
      - key: DATABASE_URL
        sync: false

  - type: worker
    name: scholarscope-beat
    env: python
    buildCommand: |
      pip install --upgrade pip setuptools wheel
      pip install -r requirements.txt
    startCommand: celery -A scholarscope beat -l info
    envVars:
      - key: REDIS_URL
        sync: false
      - key: DATABASE_URL
        sync: false
