"""
Django settings for scholarscope project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from decouple import config
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

import os
import sys

# BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SCRAPERS_DIR = os.path.join(BASE_DIR, "scholarscope_scrapers")
sys.path.append(SCRAPERS_DIR)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('DJANGO_SECRET_KEY')
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DEBUG", default=False, cast=bool)
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
ALLOWED_HOSTS = [
    'scholarscope-api.onrender.com',
    '.onrender.com', 
    'localhost',
    '127.0.0.1',
    '::',
]

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'django.contrib.sites',
    'corsheaders',
    'rest_framework',
    'rest_framework.authtoken',
    'dj_rest_auth',
    'dj_rest_auth.registration',
    'taggit',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'django_celery_results',
    'widget_tweaks',
    'django_htmx',
    'anymail',
    'scholarships.apps.ScholarshipsConfig',
    'pgvector',
    'tailwind',
    'theme',
    'drf_spectacular',
    
     ]

TAILWIND_APP_NAME='theme'
NPM_BIN_PATH = r"C:\Program Files\nodejs\npm.cmd"

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',

    'allauth.account.auth_backends.AuthenticationBackend',
]


REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'dj_rest_auth.jwt_auth.JWTCookieAuthentication',
        'rest_framework_simplejwt.authentication.JWTAuthentication',),
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],
     'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'ScholarScope API',
    'DESCRIPTION': 'Scholarship apis ',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    # OTHER SETTINGS
}
from datetime import timedelta

# djangorestframework-simplejwt
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(hours=1),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
}

# dj-rest-auth
REST_AUTH = {
    "USE_JWT": True,
    "JWT_AUTH_COOKIE": "_auth",  # Name of access token cookie
    "JWT_AUTH_REFRESH_COOKIE": "_refresh", # Name of refresh token cookie
    "JWT_AUTH_HTTPONLY": False,  # Makes sure refresh token is sent
    "LOGIN_ON_REGISTER": True,
}

# settings.py
REST_AUTH_SERIALIZERS = {
    'USER_DETAILS_SERIALIZER': 'users.serializers.UserSerializer',
}

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "allauth.account.middleware.AccountMiddleware",
     "django_htmx.middleware.HtmxMiddleware",
]
    
ROOT_URLCONF = "scholarscope.urls"
import os
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS":  [os.path.join(BASE_DIR, 'templates'), os.path.join(BASE_DIR, 'templates', 'allauth')],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "scholarscope.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': 'scholar_scope_db',
#         'USER': 'chidera',  
#         'PASSWORD': '',     
#         'HOST': 'localhost',
#         'PORT': '5432',
#     }
# }
import dj_database_url
DATABASES = {
    'default': dj_database_url.config(
        default=config('DATABASE_URL', default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}"),
        conn_max_age=600,
        conn_health_checks=True,
    )
}
# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

# STATIC_URL = "/static/"

# STATICFILES_DIRS = [
#     BASE_DIR / "static",  
# ]

# STATIC_ROOT = BASE_DIR / "staticfiles"

# STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# settings.py

STATIC_URL = "/static/"

# Use an absolute path for STATIC_ROOT
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

# Ensure STATIC_DIR points to your source files
STATIC_DIR = os.path.join(BASE_DIR, "static")

if os.path.exists(STATIC_DIR):
    STATICFILES_DIRS = [STATIC_DIR]
else:
    STATICFILES_DIRS = []

# Using WhiteNoise for production assets
STORAGES = {
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
    },
}
MEDIA_URL= 'media/'
MEDIA_ROOT= BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# SOCIALACCOUNT_PROVIDERS = {
#     'google': {
#         'APP': {
#             'client_id': config('GOOGLE_OAUTH_CLIENT_ID'),
#             'secret': config('GOOGLE_OAUTH_CLIENT_SECRET'),
#             'key': ''
#         },
#         'SCOPE': [
#             'profile',
#             'email',
#         ],
#     }
# }


# --- Authentication Settings ---
AUTH_USER_MODEL = 'scholarships.User'

# 1. Login with Email (No Username)
ACCOUNT_LOGIN_METHODS = {'email'}
ACCOUNT_EMAIL_REQUIRED = True           
ACCOUNT_UNIQUE_EMAIL = True             
ACCOUNT_USERNAME_REQUIRED = False       

# 2. Email Verification & Auto-Login
# 'optional' is perfect: It creates the user immediately (allowing auto-login)
# but still allows you to send a verification email in the background if you want.
ACCOUNT_EMAIL_VERIFICATION = 'optional' 
ACCOUNT_CONFIRM_EMAIL_ON_GET = True

# 3. Redirects
LOGIN_REDIRECT_URL = '/dashboard'
LOGOUT_REDIRECT_URL = '/login'
ACCOUNT_SIGNUP_REDIRECT_URL = '/profile' 

# --- Social Account Settings ---
SOCIALACCOUNT_ADAPTER = "scholarscope.adapters.MySocialAccountAdapter"
SOCIALACCOUNT_AUTO_SIGNUP = True
SOCIALACCOUNT_EMAIL_VERIFICATION = "none"
SOCIALACCOUNT_QUERY_EMAIL = True
SOCIALACCOUNT_LOGIN_ON_GET = True

REDIS_URL = config("REDIS_URL")

CELERY_BROKER_URL = REDIS_URL
CELERY_RESULT_BACKEND = REDIS_URL
import ssl
if REDIS_URL.startswith('rediss://'):
    CELERY_BROKER_USE_SSL = {
        'ssl_cert_reqs': ssl.CERT_NONE,
    }
    CELERY_REDIS_BACKEND_USE_SSL = {
        'ssl_cert_reqs': ssl.CERT_NONE,
    }

CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True
CELERY_BEAT_SCHEDULER='django_celery_beat.schedulers.DatabaseScheduler'
SOCIALACCOUNT_AUTO_SIGNUP = True

ANYMAIL = {
  "MAILTRAP_API_TOKEN": config("MAIL_TRAP_TOKEN"),
}
EMAIL_BACKEND = "anymail.backends.mailtrap.EmailBackend"
DEFAULT_FROM_EMAIL = "hello@demomailtrap.co"

ACCOUNT_EMAIL_SUBJECT_PREFIX = ''

GOOGLE_OAUTH_CALLBACK_URL=config('GOOGLE_OAUTH_CALLBACK_URL')
SITE_ID = 1

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": REDIS_URL, 
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
             
        }
    }
}


SITE_URL = config("SITE_URL", default="http://127.0.0.1:8000")
FRONTEND_URL = "https://scholar-scope-phi.vercel.app/"
# settings.py


# 2. ADD your exact frontend URLs here:
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",       # Local React/Next.js
    "http://localhost:5173",       # Local Vite
    "chrome-extension://ojkebjiebipjbjfpakippnkklhdddbpf", # Your Extension
    FRONTEND_URL, # <-- ADD YOUR DEPLOYED FRONTEND HERE
]

CORS_ALLOW_CREDENTIALS = True

# 3. ADD the frontend URL to CSRF trusted origins so POST requests work:
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:8000",
    "http://localhost:5173",
    "http://localhost:3000",
    "chrome-extension://ojkebjiebipjbjfpakippnkklhdddbpf",
    "https://scholarscope-api.onrender.com",
    FRONTEND_URL,
]